modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/Scarecrows/blob/1.16/LICENSE"

[[mods]] #mandatory
	modId="scarecrows" #mandatory
	version="v1.0.8" #mandatory
	displayName="Scarecrows" #mandatory
	description='''Adds scarecrows that keep monsters (and animals if you want) off your lawn.''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/Scarecrows/issues"
	displayURL="http://minecraft.curseforge.com/projects/scarecrows"
	authors="bl4ckscor3"

[[dependencies.scarecrows]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scarecrows]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"